include:
  - project: 'tauOS/ci'
    file: '/.rpm-build-template.yml'
  - project: 'tauOS/ci'
    file: '/.rpm-sign-template.yml'
  - project: 'tauOS/ci'
    file: '/.update-repo-template.yml'

variables:
    PACKAGE_VERSION: "1"
    PACKAGE_NAME: "tau-repos"
    PACKAGE_ARCH: "noarch"

stages:
  - build
  - sign
  - upload

build-job:
  stage: build
  before_script:
    - sudo dnf install -y gnupg sed
  extends: .build

sign-job:
  stage: sign
  extends: .sign

upload-job:
  stage: upload
  extends: .upload
